site_name: listmonk / Documentation
theme:
  name: material
  # custom_dir: "mkdocs-material/material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  language: "en"
  font:
    text: 'Inter'
    code: 'Ubuntu Mono'
  direction: 'ltr'
  extra:
  search:
    language: 'en, de, ru'
  feature:
    tabs: true

  palette:
    primary: "white"
    accent: "red"

site_dir: _out

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - "static/style.css"

copyright: "Copyright &copy; 2019, Kailash Nadh."

pages:
  - "Introduction": index.md
  - "Installation": installation.md
  - "Configuration": configuration.md
  - "Developer setup": developer-setup.md
  - "Concepts": concepts.md
  - "Querying and segmenting subscribers": querying-and-segmentation.md
  - "Templating": templating.md
  - "Integrating with external systems": external-integration.md
  - "API": apis/apis.md
  - "API / Subscribers": apis/subscribers.md
  - "API / Lists": apis/lists.md
  - "API / Import": apis/import.md
  - "API / Campaigns": apis/campaigns.md
  - "API / Media": apis/media.md
  - "API / Templates": apis/templates.md
  
